### PR TITLE
Fix non ckeditor field

### LINKED ISSUE #153: Editable fields gets wrapped in <P> tag
Simple input fields (like news extension title or teaser) that are used for simple text without HTML, after editing with frontend_editing get wrapped in P tag

### PR DESCRIPTION
**Pull request by anjeylink**
Fixes #153

### CODE REVIEW

File: Resources/Public/JavaScript/Crud.js [hunk 1]
```diff
@@ -65,13 +65,21 @@ define(['jquery', 'TYPO3/CMS/FrontendEditing/FrontendEditing'], function ($, Fro
 			$.when(checkIfRecordIsLocked(item)).done(function(data) {
 				// If user prompted yes or there was no locked record found
 				if (data === false) {
+					// check if it's CKEditor field and save either with html or without
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Crud.js]: // Check if the CKEditor has configuration, otherwise remove HTML tags

File: Classes/Controller/EditorController.php [hunk 2]
```diff
@@ -87,7 +87,8 @@ public function getConfigurationAction(ServerRequestInterface $request, Response
 
         $data = [
             'configuration' => $configuration,
-            'externalPlugins' => $externalPlugins
+            'externalPlugins' => $externalPlugins,
+            'isCKEditorFieldEnable' => $this->rteConfiguration !== null
```
Comment (MattiasNilsson) [inline Classes/Controller/EditorController.php]: I would rename the property to **hasCkeditorConfiguration**

File: Resources/Public/JavaScript/Editor.js [hunk 3]
```diff
@@ -26,6 +26,20 @@ define(['jquery', 'ckeditor', 'ckeditor-jquery-adapter'], function ($, CKEDITOR)
 		stylesSet: []
 	};
 
+	/**
+	 * Default simple tool bar for non CKEditor (RTE) field
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Editor.js]: Default simple toolbar for non CKEditor (RTE) field

File: Resources/Public/JavaScript/Editor.js [hunk 4]
```diff
@@ -153,7 +167,15 @@ define(['jquery', 'ckeditor', 'ckeditor-jquery-adapter'], function ($, CKEDITOR)
 				if (typeof data.externalPlugins !== 'undefined') {
 					eval(data.externalPlugins);
 				}
-				var config = $.extend(true, defaultEditorConfig, data.configuration);
+
+				// if not a CKEditor field display only copy past bar
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Editor.js]: If there is no CKEditor configuration.

File: Resources/Public/JavaScript/Editor.js [hunk 5]
```diff
@@ -153,7 +167,15 @@ define(['jquery', 'ckeditor', 'ckeditor-jquery-adapter'], function ($, CKEDITOR)
...
+				var config = defaultEditorConfig;
+				if (data.isCKEditorFieldEnable) {
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Editor.js]: data.hasCkeditorConfiguration

File: Resources/Public/JavaScript/Editor.js [hunk 6]
```diff
@@ -167,6 +189,7 @@ define(['jquery', 'ckeditor', 'ckeditor-jquery-adapter'], function ($, CKEDITOR)
 								'table': dataSet.table,
 								'uid': dataSet.uid,
 								'field': dataSet.field,
+								'isCKEditorFieldEnable': data.isCKEditorFieldEnable,
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Editor.js]: hasCkeditorConfiguration

**Comment by MattiasNilsson** [comment]
Great stuff! 👍
