### PR TITLE
Fix move content elements. Drop zone before first CE element

### LINKED ISSUE #112: Multicolumn, how to move content elements between them
Multicolumn, how to move content elements between them. There should be a ready concept for this before starting.

An alternative could be to add a button which can copy and the paste before/after depending on the scenario.

### PR DESCRIPTION
**Pull request by anjeylink**
Move content elements between columns. Create new content element before first content element. Fixes #112

### CODE REVIEW

File: Classes/Service/ContentEditableWrapperService.php [hunk 1]
```diff
@@ -87,7 +87,10 @@ public function wrapContent(string $table, int $uid, array $dataArr, string $con
         // Could make it would make it possible to configure cid for use with extensions that create columns by content
         $class = 't3-frontend-editing__inline-actions';
         $content = sprintf(
-            '<div class="t3-frontend-editing__ce %s" title="%s">' .
+            '<div class="t3-frontend-editing__ce %s" title="%s" draggable="true"' .
+                'data-movable="1"' .
```
Comment (MattiasNilsson) [inline Classes/Service/ContentEditableWrapperService.php]: moveable

File: Resources/Public/JavaScript/FrontendEditing.js [hunk 2]
```diff
@@ -130,29 +130,67 @@ define(['jquery', 'TYPO3/CMS/FrontendEditing/Storage'], function ($, Storage) {
 			}
 		},
 
-		dragNewCeStart: function (ev) {
+		dragCeStart: function (ev) {
+			var movable = parseInt(ev.currentTarget.dataset.movable, 10);
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/FrontendEditing.js]: moveable

File: Resources/Public/JavaScript/FrontendEditing.js [hunk 3]
```diff
@@ -130,29 +130,67 @@ define(['jquery', 'TYPO3/CMS/FrontendEditing/Storage'], function ($, Storage) {
...
+
 			ev.dataTransfer.setData('params', ev.currentTarget.dataset.params);
+			ev.dataTransfer.setData('movable', movable);
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/FrontendEditing.js]: moveable

File: Resources/Public/JavaScript/FrontendEditing.js [hunk 4]
```diff
@@ -130,29 +130,67 @@ define(['jquery', 'TYPO3/CMS/FrontendEditing/Storage'], function ($, Storage) {
...
+			ev.dataTransfer.setData('movableUid', $(ev.currentTarget).find('span.t3-frontend-editing__inline-actions').data('uid'));
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/FrontendEditing.js]: moveable

File: Resources/Public/JavaScript/FrontendEditing.js [hunk 5]
```diff
@@ -130,29 +130,67 @@ define(['jquery', 'TYPO3/CMS/FrontendEditing/Storage'], function ($, Storage) {
...
-		dragNewCeLeave: function (ev) {
+		dragCeLeave: function (ev) {
 			ev.preventDefault();
 			$(ev.currentTarget).removeClass('active');
 		},
 
-		dropNewCe: function (ev) {
+		dropCe: function (ev) {
 			ev.preventDefault();
+			var movable = parseInt(ev.dataTransfer.getData('movable'), 10);
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/FrontendEditing.js]: moveable

File: Resources/Public/JavaScript/FrontendEditing.js [hunk 6]
```diff
@@ -130,29 +130,67 @@ define(['jquery', 'TYPO3/CMS/FrontendEditing/Storage'], function ($, Storage) {
...
+
+			if (movable === 1) {
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/FrontendEditing.js]: moveable

File: Resources/Public/JavaScript/FrontendEditing.js [hunk 7]
```diff
@@ -130,29 +130,67 @@ define(['jquery', 'TYPO3/CMS/FrontendEditing/Storage'], function ($, Storage) {
...
+				var $currentTarget = $(ev.currentTarget);
+				var ceUid = parseInt(ev.dataTransfer.getData('movableUid'), 10);
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/FrontendEditing.js]: moveable

File: Classes/Controller/ReceiverController.php [hunk 8]
```diff
@@ -66,10 +67,15 @@ public function processRequest(ServerRequestInterface $request, ResponseInterfac
...
                     case 'move':
+                        $colPos = isset($request->getParsedBody()['colPos']) ?
+                            (int)$request->getParsedBody()['colPos'] : -2;
+
                         $this->moveAction(
                             $table,
                             $uid,
-                            (int)$request->getParsedBody()['beforeUid']
+                            (int)$request->getParsedBody()['beforeUid'],
+                            (int)$request->getQueryParams()['page'],
```
Comment (MattiasNilsson) [inline Classes/Controller/ReceiverController.php]: What is this is not set? Default value for safety

File: Classes/Controller/ReceiverController.php [hunk 9]
```diff
@@ -66,10 +67,15 @@ public function processRequest(ServerRequestInterface $request, ResponseInterfac
...
+                            $colPos
```
Comment (MattiasNilsson) [inline Classes/Controller/ReceiverController.php]: What is this is not set? Default value for safety

**Comment by MattiasNilsson** [comment]
Really nice! 👍
