### PR TITLE
Scrolling during drag fault

### LINKED ISSUE #460: Scrolling during drag fault
Hi
The "scrolling during drag" feature is not working.
https://github.com/FriendsOfTYPO3/frontend_editing/blob/3bfbaf4c8713bd388fd79c3db6eb98cef35646ac/Resources/Public/JavaScript/FrontendEditing.js#L67
Tested with FF 84 and Chromium 87 on a Linux machine.
There are several problems:

1. The drag Event seems not to have an valid clientY value
2. Mouse Events aren't working if the cursor is on an iframe (if iframe would be the target)

So i made a playground for this problem in codepen to reproduce:
https://codepen.io/messj1/pen/JjRvaoz?editors=0010

My conclusion is:

1. ... to use dragover instead of drag.
2. .. add some scrollareas to fetch the dragovers.
3. .. add dragleave on the scrollareas to prevent ghost scrolling.

As an UX improvment, it would be nice to scroll faster as more the cursor goes to the border. Additionally an acceleration would be nice.

### PR DESCRIPTION
**Pull request by Messj1**
Fixes  #460

### CODE REVIEW

File: Resources/Public/JavaScript/FrontendEditing.js [hunk 1]
```diff
@@ -52,33 +52,31 @@ define(['jquery', 'TYPO3/CMS/FrontendEditing/Storage'], function ($, Storage) {
...
+        .height(100)
+        .hide()
+        .insertAfter($iframe);
+
+    var scroller = Scroller($iframe, $iframe.contents(), $scrollAreaTop, $scrollAreaBottom);
+
+    $scrollAreaTop.on('dragleave', scroller.stopScrolling)
+		.on('dragenter', function() {
+			scroller.startScrolling(-4);
+		});
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/FrontendEditing.js:71]: Add newline.

File: Resources/Public/JavaScript/Scroller.js [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+        // Listening
+        var enabled = false;
+        // Scrolling
+        var scrolling = false;
+        var timeoutId = -1;
+        var speed = 0;
+
+        function stopScrolling() {
+            scrolling = false;
+            if(timeoutId>=0){
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Scroller.js:33]: Add missing spaces.

```suggestion
            if (timeoutId >= 0) {
```

File: Resources/Public/JavaScript/Scroller.js [hunk 3]
```diff
@@ -0,0 +1,119 @@
...
+                window.clearTimeout(timeoutId);
+            }
+        }
+
+        function startScrolling(newSpeed) {
+            if(!enabled){
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Scroller.js:39]: Add missing spaces.

```suggestion
            if (!enabled) {
```

File: Resources/Public/JavaScript/Scroller.js [hunk 4]
```diff
@@ -0,0 +1,119 @@
...
+                return;
+            }
+            stopScrolling();
+            speed = newSpeed;
+
+            if(speed!==0){
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Scroller.js:45]: Add missing spaces.

```suggestion
            if (speed !== 0) {
```

File: Resources/Public/JavaScript/Scroller.js [hunk 5]
```diff
@@ -0,0 +1,119 @@
...
+                var checkFnc;
+                var scrollY = $target.contents().scrollTop();
+                if(speed<0){
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Scroller.js:48]: Add missing spaces.

```suggestion
                if (speed < 0) {
```

File: Resources/Public/JavaScript/Scroller.js [hunk 6]
```diff
@@ -0,0 +1,119 @@
...
+                    checkFnc = checkScrollUpBound;
+                    checkScrollDownBound(scrollY+speed, true);
+                } else {
+                    checkFnc = checkScrollDownBound;
+                    checkScrollUpBound(scrollY+speed, true);
+                }
+
+                scrolling=true;
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Scroller.js:56]: Add missing spaces.

```suggestion
                scrolling = true;
```

File: Resources/Public/JavaScript/Scroller.js [hunk 7]
```diff
@@ -0,0 +1,119 @@
...
+            }
+            stopScrolling();
+            speed = newSpeed;
+
+            if(speed!==0){
+                var checkFnc;
+                var scrollY = $target.contents().scrollTop();
+                if(speed<0){
+                    checkFnc = checkScrollUpBound;
+                    checkScrollDownBound(scrollY+speed, true);
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Scroller.js:50]: Add missing spaces.

```suggestion
                    checkScrollDownBound(scrollY + speed, true);
```

File: Resources/Public/JavaScript/Scroller.js [hunk 8]
```diff
@@ -0,0 +1,119 @@
...
+                } else {
+                    checkFnc = checkScrollDownBound;
+                    checkScrollUpBound(scrollY+speed, true);
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Scroller.js:53]: Add missing spaces.

```suggestion
                    checkScrollUpBound(scrollY + speed, true);
```

File: Resources/Public/JavaScript/Scroller.js [hunk 9]
```diff
@@ -0,0 +1,119 @@
...
+                }
+
+                scrolling=true;
+                //share checkFnc variable
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Scroller.js:57]: Add missing spaces.

```suggestion
                // Share checkFnc variable
```

File: Resources/Public/JavaScript/Scroller.js [hunk 10]
```diff
@@ -0,0 +1,119 @@
...
+                        }
+                    }
+                };
+                scroll();
+
+            }
+        }
+
+        function checkScrollUpBound(scrollY){
+            if(scrollY <= 0){
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Scroller.js:75]: Add missing spaces.

```suggestion
            if (scrollY <= 0) {
```

File: Resources/Public/JavaScript/Scroller.js [hunk 11]
```diff
@@ -0,0 +1,119 @@
...
+                scrolling = false;
+            } else {
+                $scrollAreaTop.show();
+            }
+            return scrollY;
+        }
+
+        function checkScrollDownBound(scrollY){
+            var maxScroll = $target.contents().height() - $target.height();
+            if(scrollY >= maxScroll){
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Scroller.js:87]: Add missing spaces.

```suggestion
            if (scrollY >= maxScroll) {
```

File: Resources/Public/JavaScript/Scroller.js [hunk 12]
```diff
@@ -0,0 +1,119 @@
...
+                scrollY = maxScroll;
+                scrolling = false;
+            } else {
+                $scrollAreaBottom.show();
+            }
+            return scrollY;
+        }
+
+        function enable() {
+            enabled=true;
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Scroller.js:98]: Add missing spaces.

```suggestion
            enabled = true;
```

File: Resources/Public/JavaScript/Scroller.js [hunk 13]
```diff
@@ -0,0 +1,119 @@
...
+            scrolling=false;
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Scroller.js:99]: Add missing spaces.

```suggestion
            scrolling = false;
```

File: Resources/Public/JavaScript/Scroller.js [hunk 14]
```diff
@@ -0,0 +1,119 @@
...
+            var scrollY = $target.contents().scrollTop();
+            checkScrollUpBound(scrollY);
+            checkScrollDownBound(scrollY);
+        }
+
+        function disable() {
+            enabled=false;
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Scroller.js:106]: Add missing spaces.

```suggestion
            enabled = false;
```

**Review by MattiasNilsson — CHANGES_REQUESTED** [review]
Thanks for your fix, works nicely there is just some minor nitpicks to take a look at 👍

**Comment by MattiasNilsson** [comment]
Nice on!
