### PR TITLE
[BUGFIX] add scrolling while dragging CE. Fixes: #198

### LINKED ISSUE #198: HTML scroll not available while dragging CE
When I drag a CE, it's not possible to drop it in a drop area that's not visible because the page doesn't scroll.
The page should start scroll when the cursor reaches the top or the bottom area of the page.

### PR DESCRIPTION
**Pull request by mesosa**

### CODE REVIEW

File: Resources/Public/JavaScript/FrontendEditing.js [hunk 1]
```diff
@@ -49,6 +49,36 @@ define(['jquery', 'TYPO3/CMS/FrontendEditing/Storage'], function ($, Storage) {
...
+		var scrollY = $('iframe').contents().scrollTop();
+		$('iframe').contents().scrollTop(scrollY + step);
+		if (!stop) {
+		setTimeout(function() {
+			scroll(step);
+		}, 20);
+		}
+	};
+
+	$('[draggable]').on("drag", function(e) {
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/FrontendEditing.js]: Use single quotes and not double.

File: Resources/Public/JavaScript/FrontendEditing.js [hunk 2]
```diff
@@ -49,6 +49,36 @@ define(['jquery', 'TYPO3/CMS/FrontendEditing/Storage'], function ($, Storage) {
...
+		}
+
+		if (e.originalEvent.clientY > ($(document).height() - 100)) {
+			stop = false;
+			scroll(1);
+		}
+
+	});
+
+	$('[draggable]').on("dragend", function(e) {
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/FrontendEditing.js]: Use single quotes and not double.

File: Resources/Public/JavaScript/FrontendEditing.js [hunk 3]
```diff
@@ -49,6 +49,36 @@ define(['jquery', 'TYPO3/CMS/FrontendEditing/Storage'], function ($, Storage) {
 		FrontendEditing.events[key] = value;
 	};
 
+	// Scroll function when draging content elements to top or bottom of window
+	var stop = true;
+	var scroll = function(step) {
+		var scrollY = $('iframe').contents().scrollTop();
+		$('iframe').contents().scrollTop(scrollY + step);
+		if (!stop) {
+		setTimeout(function() {
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/FrontendEditing.js]: Add indent to this piece(s)

File: Resources/Public/JavaScript/FrontendEditing.js (hunk 1 above)
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/FrontendEditing.js]: Rename the e to be event, for more clarity.

**Comment by MattiasNilsson** [comment]
Nice 👍
