### PR TITLE
[BUGFIX] Prevent error when editing disallowed CE

### LINKED ISSUE #552: Error 500 when CE is not allowed
Hi!

I get an error 500 when a page contains content elements that the user is not allowed to edit. The error message reads:

> Could not fetch editor configurations due to a request error. (500, "error")

and in protocol:

> Core: Exception handler (WEB): Uncaught TYPO3 Exception: #1437687404: ERROR: authMode "explicitAllow" failed for field "CType" with value "menu_card_dir" evaluated | TYPO3\CMS\Backend\Form\Exception\AccessDeniedEditInternalsException thrown in file /[...]/public/typo3/sysext/backend/Classes/Form/FormDataProvider/DatabaseUserPermissionCheck.php in line 157. Requested URL: https://[...]/typo3/index.php?route=%2Fajax%2Ffrontend-editing%2Feditor-configuration&token=--AnonymizedToken--&page=6

### PR DESCRIPTION
**Pull request by mabolek**
When a non-admin user was editing a page with a content element the user was not allowed to edit, a 500 error would be shown. It was caused by an AccessDeniedEditInternalsException (1437687404) within DatabaseUserPermissionCheck.

Fixes #552

### CODE REVIEW

File: Resources/Public/JavaScript/Editor.js [hunk 1]
```diff
@@ -277,6 +277,12 @@ define([
 
           var elementData = data.configurations[data.elementToConfiguration[elementIdentifier]];
 
+          console.log(typeof elementData);
```
Comment (MattiasNilsson) [inline Resources/Public/JavaScript/Editor.js:280]: Remove console.log.

**Review by MattiasNilsson — CHANGES_REQUESTED** [review]

**Comment by mabolek** [comment]
@MattiasNilsson To make sure it really resolves the issue, we're testing this on a site now.
